/**
 * The standard property universe, used as the property-coverage denominator.
 *
 * A curated subset of the common IFC4 `Pset_*Common` properties and the
 * `Qto_*BaseQuantities` families, maintained by hand.
 *
 * It should be generated instead. buildingSMART publishes the definitions as
 * XML in `buildingSMART/IFC4.x-development`, under
 * `reference_schemas/psd_IFC4_ADD2_TC1/`: 513 sets for exactly the schema
 * version this profile targets.
 *
 * Until that happens the coverage percentage is substantially overstated, since
 * this denominator is a fraction of the real one. See `README.md` here.
 */
export const IFC_STANDARD_PROPERTIES: string[] = [
  // ── Pset_WallCommon ──
  "Pset_WallCommon.Reference",
  "Pset_WallCommon.Status",
  "Pset_WallCommon.IsExternal",
  "Pset_WallCommon.LoadBearing",
  "Pset_WallCommon.ExtendToStructure",
  "Pset_WallCommon.FireRating",
  "Pset_WallCommon.AcousticRating",
  "Pset_WallCommon.ThermalTransmittance",
  "Pset_WallCommon.Combustible",
  "Pset_WallCommon.SurfaceSpreadOfFlame",
  "Pset_WallCommon.Compartmentation",
  // ── Pset_SlabCommon ──
  "Pset_SlabCommon.Reference",
  "Pset_SlabCommon.Status",
  "Pset_SlabCommon.IsExternal",
  "Pset_SlabCommon.LoadBearing",
  "Pset_SlabCommon.FireRating",
  "Pset_SlabCommon.AcousticRating",
  "Pset_SlabCommon.ThermalTransmittance",
  "Pset_SlabCommon.Combustible",
  "Pset_SlabCommon.Compartmentation",
  "Pset_SlabCommon.PitchAngle",
  // ── Pset_ColumnCommon ──
  "Pset_ColumnCommon.Reference",
  "Pset_ColumnCommon.Status",
  "Pset_ColumnCommon.Slope",
  "Pset_ColumnCommon.IsExternal",
  "Pset_ColumnCommon.LoadBearing",
  "Pset_ColumnCommon.FireRating",
  // ── Pset_BeamCommon ──
  "Pset_BeamCommon.Reference",
  "Pset_BeamCommon.Status",
  "Pset_BeamCommon.Span",
  "Pset_BeamCommon.Slope",
  "Pset_BeamCommon.IsExternal",
  "Pset_BeamCommon.LoadBearing",
  "Pset_BeamCommon.FireRating",
  // ── Pset_DoorCommon ──
  "Pset_DoorCommon.Reference",
  "Pset_DoorCommon.Status",
  "Pset_DoorCommon.IsExternal",
  "Pset_DoorCommon.FireRating",
  "Pset_DoorCommon.AcousticRating",
  "Pset_DoorCommon.SecurityRating",
  "Pset_DoorCommon.ThermalTransmittance",
  "Pset_DoorCommon.FireExit",
  "Pset_DoorCommon.SelfClosing",
  "Pset_DoorCommon.SmokeStop",
  "Pset_DoorCommon.HandicapAccessible",
  // ── Pset_WindowCommon ──
  "Pset_WindowCommon.Reference",
  "Pset_WindowCommon.Status",
  "Pset_WindowCommon.IsExternal",
  "Pset_WindowCommon.FireRating",
  "Pset_WindowCommon.AcousticRating",
  "Pset_WindowCommon.SecurityRating",
  "Pset_WindowCommon.ThermalTransmittance",
  "Pset_WindowCommon.GlazingAreaFraction",
  "Pset_WindowCommon.Infiltration",
  "Pset_WindowCommon.SmokeStop",
  // ── Pset_CoveringCommon ──
  "Pset_CoveringCommon.Reference",
  "Pset_CoveringCommon.Status",
  "Pset_CoveringCommon.AcousticRating",
  "Pset_CoveringCommon.FireRating",
  "Pset_CoveringCommon.Combustible",
  "Pset_CoveringCommon.SurfaceSpreadOfFlame",
  "Pset_CoveringCommon.ThermalTransmittance",
  "Pset_CoveringCommon.Finish",
  "Pset_CoveringCommon.TotalThickness",
  // ── Pset_RoofCommon ──
  "Pset_RoofCommon.Reference",
  "Pset_RoofCommon.Status",
  "Pset_RoofCommon.IsExternal",
  "Pset_RoofCommon.FireRating",
  "Pset_RoofCommon.ThermalTransmittance",
  "Pset_RoofCommon.ProjectedArea",
  // ── Pset_StairCommon ──
  "Pset_StairCommon.Reference",
  "Pset_StairCommon.Status",
  "Pset_StairCommon.NumberOfRiser",
  "Pset_StairCommon.NumberOfTreads",
  "Pset_StairCommon.RiserHeight",
  "Pset_StairCommon.TreadLength",
  "Pset_StairCommon.FireRating",
  "Pset_StairCommon.HandicapAccessible",
  "Pset_StairCommon.FireExit",
  // ── Pset_RampCommon ──
  "Pset_RampCommon.Reference",
  "Pset_RampCommon.Status",
  "Pset_RampCommon.RequiredSlope",
  "Pset_RampCommon.HandicapAccessible",
  "Pset_RampCommon.FireExit",
  // ── Pset_RailingCommon ──
  "Pset_RailingCommon.Reference",
  "Pset_RailingCommon.Status",
  "Pset_RailingCommon.Height",
  "Pset_RailingCommon.Diameter",
  // ── Pset_CurtainWallCommon ──
  "Pset_CurtainWallCommon.Reference",
  "Pset_CurtainWallCommon.Status",
  "Pset_CurtainWallCommon.IsExternal",
  "Pset_CurtainWallCommon.FireRating",
  "Pset_CurtainWallCommon.ThermalTransmittance",
  "Pset_CurtainWallCommon.AcousticRating",
  // ── Pset_PlateCommon ──
  "Pset_PlateCommon.Reference",
  "Pset_PlateCommon.Status",
  "Pset_PlateCommon.IsExternal",
  "Pset_PlateCommon.LoadBearing",
  "Pset_PlateCommon.FireRating",
  "Pset_PlateCommon.ThermalTransmittance",
  // ── Pset_MemberCommon ──
  "Pset_MemberCommon.Reference",
  "Pset_MemberCommon.Status",
  "Pset_MemberCommon.Span",
  "Pset_MemberCommon.Slope",
  "Pset_MemberCommon.Roll",
  "Pset_MemberCommon.IsExternal",
  "Pset_MemberCommon.LoadBearing",
  "Pset_MemberCommon.FireRating",
  // ── Pset_SpaceOccupancyRequirements ──
  "Pset_SpaceOccupancyRequirements.OccupancyType",
  "Pset_SpaceOccupancyRequirements.OccupancyNumber",
  "Pset_SpaceOccupancyRequirements.OccupancyNumberPeak",
  "Pset_SpaceOccupancyRequirements.OccupancyTimePerDay",
  "Pset_SpaceOccupancyRequirements.AreaPerOccupant",
  "Pset_SpaceOccupancyRequirements.MinimumHeadroom",
  // ── Pset_SpaceCommon ──
  "Pset_SpaceCommon.Reference",
  "Pset_SpaceCommon.Status",
  "Pset_SpaceCommon.IsExternal",
  "Pset_SpaceCommon.PubliclyAccessible",
  "Pset_SpaceCommon.HandicapAccessible",
  "Pset_SpaceCommon.OccupancyType",
  "Pset_SpaceCommon.OccupancyNumber",
  "Pset_SpaceCommon.NetPlannedArea",
  "Pset_SpaceCommon.GrossPlannedArea",
  "Pset_SpaceCommon.ConcealedFlooring",
  "Pset_SpaceCommon.ConcealedCeiling",
  // ── Pset_BuildingCommon ──
  "Pset_BuildingCommon.Reference",
  "Pset_BuildingCommon.BuildingID",
  "Pset_BuildingCommon.IsPermanentID",
  "Pset_BuildingCommon.OccupancyType",
  "Pset_BuildingCommon.GrossPlannedArea",
  "Pset_BuildingCommon.NetPlannedArea",
  "Pset_BuildingCommon.NumberOfStoreys",
  "Pset_BuildingCommon.YearOfConstruction",
  "Pset_BuildingCommon.IsLandmarked",
  // ── Pset_BuildingStoreyCommon ──
  "Pset_BuildingStoreyCommon.Reference",
  "Pset_BuildingStoreyCommon.Status",
  "Pset_BuildingStoreyCommon.EntranceLevel",
  "Pset_BuildingStoreyCommon.AboveGround",
  "Pset_BuildingStoreyCommon.GrossPlannedArea",
  "Pset_BuildingStoreyCommon.NetPlannedArea",
  "Pset_BuildingStoreyCommon.LoadBearingCapacity",
  // ── Pset_SiteCommon ──
  "Pset_SiteCommon.Reference",
  "Pset_SiteCommon.BuildableArea",
  "Pset_SiteCommon.SiteCoverageRatio",
  "Pset_SiteCommon.FloorAreaRatio",
  "Pset_SiteCommon.TotalArea",
  // ── Qto_WallBaseQuantities ──
  "Qto_WallBaseQuantities.Length",
  "Qto_WallBaseQuantities.Width",
  "Qto_WallBaseQuantities.Height",
  "Qto_WallBaseQuantities.GrossFootprintArea",
  "Qto_WallBaseQuantities.NetFootprintArea",
  "Qto_WallBaseQuantities.GrossSideArea",
  "Qto_WallBaseQuantities.NetSideArea",
  "Qto_WallBaseQuantities.GrossVolume",
  "Qto_WallBaseQuantities.NetVolume",
  // ── Qto_SlabBaseQuantities ──
  "Qto_SlabBaseQuantities.Width",
  "Qto_SlabBaseQuantities.Length",
  "Qto_SlabBaseQuantities.Depth",
  "Qto_SlabBaseQuantities.Perimeter",
  "Qto_SlabBaseQuantities.GrossArea",
  "Qto_SlabBaseQuantities.NetArea",
  "Qto_SlabBaseQuantities.GrossVolume",
  "Qto_SlabBaseQuantities.NetVolume",
  "Qto_SlabBaseQuantities.GrossWeight",
  "Qto_SlabBaseQuantities.NetWeight",
  // ── Qto_SpaceBaseQuantities ──
  "Qto_SpaceBaseQuantities.Height",
  "Qto_SpaceBaseQuantities.FinishCeilingHeight",
  "Qto_SpaceBaseQuantities.FinishFloorHeight",
  "Qto_SpaceBaseQuantities.NetPerimeter",
  "Qto_SpaceBaseQuantities.GrossPerimeter",
  "Qto_SpaceBaseQuantities.GrossFloorArea",
  "Qto_SpaceBaseQuantities.NetFloorArea",
  "Qto_SpaceBaseQuantities.GrossWallArea",
  "Qto_SpaceBaseQuantities.NetWallArea",
  "Qto_SpaceBaseQuantities.GrossCeilingArea",
  "Qto_SpaceBaseQuantities.NetCeilingArea",
  "Qto_SpaceBaseQuantities.NetCeilingHeight",
  "Qto_SpaceBaseQuantities.GrossVolume",
  "Qto_SpaceBaseQuantities.NetVolume",
  // ── Qto_ColumnBaseQuantities ──
  "Qto_ColumnBaseQuantities.Length",
  "Qto_ColumnBaseQuantities.CrossSectionArea",
  "Qto_ColumnBaseQuantities.OuterSurfaceArea",
  "Qto_ColumnBaseQuantities.GrossVolume",
  "Qto_ColumnBaseQuantities.NetVolume",
  "Qto_ColumnBaseQuantities.GrossWeight",
  "Qto_ColumnBaseQuantities.NetWeight",
  // ── Qto_BeamBaseQuantities ──
  "Qto_BeamBaseQuantities.Length",
  "Qto_BeamBaseQuantities.CrossSectionArea",
  "Qto_BeamBaseQuantities.OuterSurfaceArea",
  "Qto_BeamBaseQuantities.GrossVolume",
  "Qto_BeamBaseQuantities.NetVolume",
  "Qto_BeamBaseQuantities.GrossWeight",
  "Qto_BeamBaseQuantities.NetWeight",
  // ── Qto_DoorBaseQuantities / Qto_WindowBaseQuantities ──
  "Qto_DoorBaseQuantities.Width",
  "Qto_DoorBaseQuantities.Height",
  "Qto_DoorBaseQuantities.Area",
  "Qto_DoorBaseQuantities.Perimeter",
  "Qto_WindowBaseQuantities.Width",
  "Qto_WindowBaseQuantities.Height",
  "Qto_WindowBaseQuantities.Area",
  "Qto_WindowBaseQuantities.Perimeter",
  // ── Qto_CoveringBaseQuantities ──
  "Qto_CoveringBaseQuantities.Width",
  "Qto_CoveringBaseQuantities.Length",
  "Qto_CoveringBaseQuantities.GrossArea",
  "Qto_CoveringBaseQuantities.NetArea",
  // ── Qto_MemberBaseQuantities ──
  "Qto_MemberBaseQuantities.Length",
  "Qto_MemberBaseQuantities.CrossSectionArea",
  "Qto_MemberBaseQuantities.OuterSurfaceArea",
  "Qto_MemberBaseQuantities.GrossVolume",
  "Qto_MemberBaseQuantities.NetVolume",
  "Qto_MemberBaseQuantities.GrossWeight",
  "Qto_MemberBaseQuantities.NetWeight",
  // ── Qto_PlateBaseQuantities ──
  "Qto_PlateBaseQuantities.Width",
  "Qto_PlateBaseQuantities.Perimeter",
  "Qto_PlateBaseQuantities.GrossArea",
  "Qto_PlateBaseQuantities.NetArea",
  "Qto_PlateBaseQuantities.GrossVolume",
  "Qto_PlateBaseQuantities.NetVolume",
  // ── Qto_RailingBaseQuantities ──
  "Qto_RailingBaseQuantities.Length",
  // ── Qto_BuildingStoreyBaseQuantities ──
  "Qto_BuildingStoreyBaseQuantities.GrossHeight",
  "Qto_BuildingStoreyBaseQuantities.NetHeight",
  "Qto_BuildingStoreyBaseQuantities.GrossPerimeter",
  "Qto_BuildingStoreyBaseQuantities.GrossFloorArea",
  "Qto_BuildingStoreyBaseQuantities.NetFloorArea",
  "Qto_BuildingStoreyBaseQuantities.GrossVolume",
  "Qto_BuildingStoreyBaseQuantities.NetVolume",
];
